// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The view specifies a subset of [Task][google.cloud.tasks.v2beta3.Task] data.
//
// When a task is returned in a response, not all
// information is retrieved by default because some data, such as
// payloads, might be desirable to return only when needed because
// of its large size or because of the sensitivity of data that it
// contains.
type Task_View int32

const (
	// Unspecified. Defaults to BASIC.
	Task_VIEW_UNSPECIFIED Task_View = 0
	// The basic view omits fields which can be large or can contain
	// sensitive data.
	//
	// This view does not include the
	// [body in AppEngineHttpRequest][google.cloud.tasks.v2beta3.AppEngineHttpRequest.body].
	// Bodies are desirable to return only when needed, because they
	// can be large and because of the sensitivity of the data that you
	// choose to store in it.
	Task_BASIC Task_View = 1
	// All information is returned.
	//
	// Authorization for [FULL][google.cloud.tasks.v2beta3.Task.View.FULL] requires
	// `cloudtasks.tasks.fullView` [Google IAM](https://cloud.google.com/iam/)
	// permission on the [Queue][google.cloud.tasks.v2beta3.Queue] resource.
	Task_FULL Task_View = 2
)

var Task_View_name = map[int32]string{
	0: "VIEW_UNSPECIFIED",
	1: "BASIC",
	2: "FULL",
}

var Task_View_value = map[string]int32{
	"VIEW_UNSPECIFIED": 0,
	"BASIC":            1,
	"FULL":             2,
}

func (x Task_View) String() string {
	return proto.EnumName(Task_View_name, int32(x))
}

func (Task_View) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0, 0}
}

// A unit of scheduled work.
type Task struct {
	// Optionally caller-specified in [CreateTask][google.cloud.tasks.v2beta3.CloudTasks.CreateTask].
	//
	// The task name.
	//
	// The task name must have the following format:
	// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID/tasks/TASK_ID`
	//
	// * `PROJECT_ID` can contain letters ([A-Za-z]), numbers ([0-9]),
	//    hyphens (-), colons (:), or periods (.).
	// * `LOCATION_ID` is the canonical ID for the task's location.
	//    The list of available locations can be obtained by calling
	// * `QUEUE_ID` can contain letters ([A-Za-z]), numbers ([0-9]), or
	//   hyphens (-). The maximum length is 100 characters.
	// * `TASK_ID` can contain only letters ([A-Za-z]), numbers ([0-9]),
	//   hyphens (-), or underscores (_). The maximum length is 500 characters.
	Name        string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HttpRequest *HttpRequest `protobuf:"bytes,2,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	// The time when the task is scheduled to be attempted.
	//
	// For App Engine queues, this is when the task will be attempted or retried.
	//
	// `schedule_time` will be truncated to the nearest microsecond.
	ScheduleTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`
	// Output only. The time that the task was created.
	//
	// `create_time` will be truncated to the nearest second.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The deadline for requests sent to the worker. If the worker does not
	// respond by this deadline then the request is cancelled and the attempt
	// is marked as a `DEADLINE_EXCEEDED` failure. Cloud Tasks will retry the
	// task according to the [RetryConfig][google.cloud.tasks.v2beta3.RetryConfig].
	//
	// Note that when the request is cancelled, Cloud Tasks will stop listing for
	// the response, but whether the worker stops processing depends on the
	// worker. For example, if the worker is stuck, it may not react to cancelled
	// requests.
	//
	// The default and maximum values depend on the type of request:
	//
	// * For [HTTP tasks][google.cloud.tasks.v2beta3.HttpRequest], the default is 10 minutes. The deadline
	//   must be in the interval [15 seconds, 30 minutes].
	//
	// `dispatch_deadline` will be truncated to the nearest millisecond. The
	// deadline is an approximate deadline.
	DispatchDeadline *duration.Duration `protobuf:"bytes,5,opt,name=dispatch_deadline,json=dispatchDeadline,proto3" json:"dispatch_deadline,omitempty"`
	// Output only. The number of attempts dispatched.
	//
	// This count includes attempts which have been dispatched but haven't
	// received a response.
	DispatchCount int32 `protobuf:"varint,6,opt,name=dispatch_count,json=dispatchCount,proto3" json:"dispatch_count,omitempty"`
	// Output only. The number of attempts which have received a response.
	ResponseCount int32 `protobuf:"varint,7,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
	// Output only. The status of the task's first attempt.
	//
	// Only [dispatch_time][google.cloud.tasks.v2beta3.Attempt.dispatch_time] will be set.
	// The other [Attempt][google.cloud.tasks.v2beta3.Attempt] information is not retained by Cloud Tasks.
	FirstAttempt *Attempt `protobuf:"bytes,8,opt,name=first_attempt,json=firstAttempt,proto3" json:"first_attempt,omitempty"`
	// Output only. The status of the task's last attempt.
	LastAttempt *Attempt `protobuf:"bytes,9,opt,name=last_attempt,json=lastAttempt,proto3" json:"last_attempt,omitempty"`
	// Output only. The view specifies which subset of the [Task][google.cloud.tasks.v2beta3.Task] has
	// been returned.
	View                 Task_View `protobuf:"varint,10,opt,name=view,proto3,enum=api.Task_View" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetHttpRequest() *HttpRequest {
	if m != nil {
		return m.HttpRequest
	}
	return nil
}

func (m *Task) GetScheduleTime() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *Task) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Task) GetDispatchDeadline() *duration.Duration {
	if m != nil {
		return m.DispatchDeadline
	}
	return nil
}

func (m *Task) GetDispatchCount() int32 {
	if m != nil {
		return m.DispatchCount
	}
	return 0
}

func (m *Task) GetResponseCount() int32 {
	if m != nil {
		return m.ResponseCount
	}
	return 0
}

func (m *Task) GetFirstAttempt() *Attempt {
	if m != nil {
		return m.FirstAttempt
	}
	return nil
}

func (m *Task) GetLastAttempt() *Attempt {
	if m != nil {
		return m.LastAttempt
	}
	return nil
}

func (m *Task) GetView() Task_View {
	if m != nil {
		return m.View
	}
	return Task_VIEW_UNSPECIFIED
}

// The status of a task attempt.
type Attempt struct {
	// Output only. The time that this attempt was scheduled.
	//
	// `schedule_time` will be truncated to the nearest microsecond.
	ScheduleTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`
	// Output only. The time that this attempt was dispatched.
	//
	// `dispatch_time` will be truncated to the nearest microsecond.
	DispatchTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dispatch_time,json=dispatchTime,proto3" json:"dispatch_time,omitempty"`
	// Output only. The time that this attempt response was received.
	//
	// `response_time` will be truncated to the nearest microsecond.
	ResponseTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	// Output only. The response from the worker for this attempt.
	//
	// If `response_time` is unset, then the task has not been attempted or is
	// currently running and the `response_status` field is meaningless.
	ResponseStatus       *status.Status `protobuf:"bytes,4,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Attempt) Reset()         { *m = Attempt{} }
func (m *Attempt) String() string { return proto.CompactTextString(m) }
func (*Attempt) ProtoMessage()    {}
func (*Attempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *Attempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attempt.Unmarshal(m, b)
}
func (m *Attempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attempt.Marshal(b, m, deterministic)
}
func (m *Attempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attempt.Merge(m, src)
}
func (m *Attempt) XXX_Size() int {
	return xxx_messageInfo_Attempt.Size(m)
}
func (m *Attempt) XXX_DiscardUnknown() {
	xxx_messageInfo_Attempt.DiscardUnknown(m)
}

var xxx_messageInfo_Attempt proto.InternalMessageInfo

func (m *Attempt) GetScheduleTime() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduleTime
	}
	return nil
}

func (m *Attempt) GetDispatchTime() *timestamp.Timestamp {
	if m != nil {
		return m.DispatchTime
	}
	return nil
}

func (m *Attempt) GetResponseTime() *timestamp.Timestamp {
	if m != nil {
		return m.ResponseTime
	}
	return nil
}

func (m *Attempt) GetResponseStatus() *status.Status {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Task_View", Task_View_name, Task_View_value)
	proto.RegisterType((*Task)(nil), "api.Task")
	proto.RegisterType((*Attempt)(nil), "api.Attempt")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xea, 0xb4, 0xcd, 0xc4, 0x09, 0x66, 0x55, 0x81, 0xc9, 0x01, 0xa2, 0x48, 0x48,
	0x39, 0x6d, 0xd4, 0xf6, 0xc8, 0xa1, 0x6a, 0xf3, 0x47, 0x44, 0xaa, 0x10, 0x72, 0xda, 0x72, 0x8c,
	0xb6, 0xf6, 0x36, 0xb1, 0x1a, 0x7b, 0x17, 0xef, 0x98, 0x8a, 0x47, 0xe0, 0x25, 0x78, 0x56, 0xe4,
	0xfd, 0x63, 0x10, 0x45, 0x2a, 0xdc, 0x3c, 0xdf, 0x7e, 0xbf, 0xcf, 0xa3, 0x99, 0x5d, 0x00, 0x64,
	0xea, 0x9e, 0xca, 0x52, 0xa0, 0x20, 0x7b, 0x4c, 0x66, 0x83, 0x37, 0x1b, 0x21, 0x36, 0x3b, 0x3e,
	0xd1, 0xd2, 0x6d, 0x75, 0x37, 0x49, 0xab, 0x92, 0x61, 0x26, 0x0a, 0x63, 0x1a, 0xbc, 0xfd, 0xf3,
	0x1c, 0xb3, 0x9c, 0x2b, 0x64, 0xb9, 0xb4, 0x86, 0x57, 0xd6, 0x50, 0xca, 0x64, 0xa2, 0x90, 0x61,
	0xa5, 0xec, 0x41, 0x80, 0xac, 0xdc, 0x70, 0x34, 0xd5, 0xe8, 0x87, 0x0f, 0xfe, 0x15, 0x53, 0xf7,
	0x84, 0x80, 0x5f, 0xb0, 0x9c, 0x47, 0xde, 0xd0, 0x1b, 0x77, 0x62, 0xfd, 0x4d, 0x4e, 0x21, 0xd8,
	0x22, 0xca, 0x75, 0xc9, 0xbf, 0x54, 0x5c, 0x61, 0xd4, 0x1a, 0x7a, 0xe3, 0xee, 0x49, 0x48, 0x99,
	0xcc, 0xe8, 0x07, 0x44, 0x19, 0x1b, 0x3d, 0xee, 0x6e, 0x7f, 0x15, 0xe4, 0x0c, 0x7a, 0x2a, 0xd9,
	0xf2, 0xb4, 0xda, 0xf1, 0x75, 0xdd, 0x54, 0xb4, 0xa7, 0xa9, 0x01, 0x35, 0x0d, 0x51, 0xd7, 0x31,
	0xbd, 0x72, 0x1d, 0xc7, 0x81, 0x03, 0x6a, 0x89, 0xbc, 0x87, 0x6e, 0x52, 0x72, 0x86, 0x16, 0xf7,
	0x9f, 0xc4, 0xc1, 0xd8, 0x35, 0xbc, 0x80, 0x17, 0x69, 0xa6, 0x24, 0xc3, 0x64, 0xbb, 0x4e, 0x39,
	0x4b, 0x77, 0x59, 0xc1, 0xa3, 0xb6, 0x8e, 0x78, 0xfd, 0x28, 0x62, 0x66, 0x67, 0x1a, 0x87, 0x8e,
	0x99, 0x59, 0x84, 0xbc, 0x83, 0x7e, 0x93, 0x93, 0x88, 0xaa, 0xc0, 0x68, 0x7f, 0xe8, 0x8d, 0xdb,
	0x71, 0xcf, 0xa9, 0xd3, 0x5a, 0xac, 0x6d, 0x25, 0x57, 0x52, 0x14, 0x8a, 0x5b, 0xdb, 0x81, 0xb1,
	0x39, 0xd5, 0xd8, 0x8e, 0xa1, 0x77, 0x97, 0x95, 0x0a, 0xd7, 0x0c, 0x91, 0xe7, 0x12, 0xa3, 0x43,
	0xdd, 0x51, 0xa0, 0x27, 0x79, 0x6e, 0xb4, 0x38, 0xd0, 0x16, 0x5b, 0x91, 0x09, 0x04, 0x3b, 0xf6,
	0x1b, 0xd1, 0xf9, 0x0b, 0xd1, 0xad, 0x1d, 0x0e, 0x18, 0x81, 0xff, 0x35, 0xe3, 0x0f, 0x11, 0x0c,
	0xbd, 0x71, 0xff, 0xa4, 0xaf, 0x8d, 0xf5, 0x66, 0xe9, 0x4d, 0xc6, 0x1f, 0x62, 0x7d, 0x36, 0x3a,
	0x06, 0xbf, 0xae, 0xc8, 0x11, 0x84, 0x37, 0xcb, 0xf9, 0xe7, 0xf5, 0xf5, 0xc7, 0xd5, 0xa7, 0xf9,
	0x74, 0xb9, 0x58, 0xce, 0x67, 0xe1, 0x33, 0xd2, 0x81, 0xf6, 0xc5, 0xf9, 0x6a, 0x39, 0x0d, 0x3d,
	0x72, 0x08, 0xfe, 0xe2, 0xfa, 0xf2, 0x32, 0x6c, 0x8d, 0xbe, 0xb7, 0xe0, 0xc0, 0xfd, 0xe2, 0xd1,
	0x6a, 0xbd, 0xff, 0x5c, 0xed, 0x19, 0x34, 0xf3, 0x33, 0x01, 0xad, 0xa7, 0x03, 0x1c, 0xe0, 0x02,
	0x9a, 0x79, 0xff, 0xeb, 0xe5, 0x72, 0x80, 0xbd, 0x5c, 0xcf, 0x9b, 0x00, 0xf3, 0x2c, 0xec, 0x05,
	0x23, 0x2e, 0xa2, 0x94, 0x09, 0x5d, 0xe9, 0x93, 0xb8, 0xd9, 0xad, 0xa9, 0x2f, 0x5e, 0xc2, 0x51,
	0x22, 0x72, 0x2a, 0x0a, 0xbe, 0x11, 0x94, 0xa9, 0x6f, 0x45, 0x52, 0x3f, 0x5b, 0x75, 0xbb, 0xaf,
	0x7f, 0x7b, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xcb, 0xfa, 0xfa, 0xc6, 0x03, 0x00, 0x00,
}
